### PR TITLE
Added recipe for reading elements of an array, with error checking

### PR DESCRIPTION
**Pull request by emilyviolet**
Added a quick recipe for reading elements from a TOML array, as mentioned in issue #70. This should probably go in `table.rst` created in PR #80 so it might be best to wait until that PR is complete, then I can modify this one (this is just a suggestion though, happy to defer if you'd rather do it another way).

### CODE REVIEW

**Comment by awvwgk** [comment]
I think having a separate recipe dealing with arrays is useful. Aspects like nested arrays (lists of lists rather than multidimensional arrays) or mixed type arrays can be discussed here.

**Comment by awvwgk** [comment]
I mostly finished the recipes on tables now. Also, I went ahead and updated the code snippet to be runable with fpm to allow easy verification of the example code. Let me know if you have any question.

**Comment by emilyviolet** [comment]
Sounds good! Thanks for adding the fpm files, too. I've added another section for nested array-of-arrays and reorganised the example programs to separate them based on what concept they're demonstrating.

**Review by awvwgk — APPROVED** [review]
Thanks for sharing, I just added some minor formatting changes.

I also updated the tip on the incompatible types, the value argument is `intent(out)`, which means the default value will be dependent on the compiler options. In most cases this is actually zero, but not guaranteed.

**Pull request merged**
